/** Deep area lists for Lagos and FCT (Abuja) — Jiji-style coverage. */
export const LAGOS_AREAS = [
  'Agege',
  'Agboyi',
  'Aguda',
  'Ajah',
  'Ajegunle',
  'Alimosho',
  'Amuwo Odofin',
  'Anthony',
  'Apapa',
  'Awoyaya',
  'Badagry',
  'Banana Island',
  'Bariga',
  'Berger',
  'Chevron',
  'Coker',
  'Egbeda',
  'Ejigbo',
  'Epe',
  'Eti-Osa',
  'Festac',
  'Gbagada',
  'Ibeju-Lekki',
  'Idi-Araba',
  'Idimu',
  'Ifako-Ijaiye',
  'Igando',
  'Ikeja',
  'Ikorodu',
  'Ikotun',
  'Ikoyi',
  'Ilashe',
  'Ilupeju',
  'Ipaja',
  'Isheri',
  'Isolo',
  'Jakande',
  'Ketu',
  'Lekki',
  'Lekki Phase 1',
  'Lekki Phase 2',
  'Magboro',
  'Magodo',
  'Maryland',
  'Mile 12',
  'Mile 2',
  'Mowe',
  'Mushin',
  'Obalende',
  'Ogba',
  'Ogudu',
  'Ojo',
  'Ojota',
  'Okota',
  'Oniru',
  'Oregun',
  'Orile',
  'Oshodi',
  'Palmgrove',
  'Sangotedo',
  'Satellite Town',
  'Shomolu',
  'Surulere',
  'Trade Fair',
  'Victoria Island',
  'Yaba',
] as const;

export const FCT_AREAS = [
  'Abuja',
  'Apo',
  'Asokoro',
  'Bwari',
  'Central Area',
  'Dawaki',
  'Dei-Dei',
  'Durumi',
  'Dutse',
  'Galadimawa',
  'Garki',
  'Gwarinpa',
  'Gwagwa',
  'Jabi',
  'Kado',
  'Karu',
  'Karsana',
  'Kubwa',
  'Kuje',
  'Life Camp',
  'Lokogoma',
  'Lugbe',
  'Maitama',
  'Mpape',
  'Nyanya',
  'Utako',
  'Wuse',
  'Wuse 2',
] as const;

/** Labels that should stay aliases only — never separate catalog nodes. */
export const ALIAS_ONLY_AREA_LABELS = new Set(['ph', 'vi']);
