export const colors = {
  primary: '#E68032',
  primaryHover: '#B86627',
  accent: '#b9511b',
  accentDark: '#8f3b12',
  accentStrong: '#ce5f18',
  accentLink: '#E68032',
  accentBright: '#f06d21',
  accentButton: '#ef812d',
  accentMark: '#f5822c',
  accentSoft: '#fff3ec',
  accentTint: '#fff8f2',
  accentWash: '#fff9f4',

  ink: '#111111',
  inkSoft: '#18181a',
  inkMuted: '#1f1f21',
  inkPanel: '#202020',
  inkBody: '#242424',
  inkLine: '#2a2a2a',
  inkGradient: '#1b1b1b',
  black: '#050505',
  appleBlack: '#161616',

  paper: '#ffffff',
  white: '#fff',
  soft: '#f6f7f8',
  page: '#f7f7f8',
  surfaceSubtle: '#fafafa',
  surfaceRaised: '#fbfbfb',
  inputSoft: '#f0efee',

  line: '#e7e2de',
  lineLight: '#dedede',
  lineSofter: '#dedee2',
  lineMuted: '#d7d7d7',
  navMuted: '#d8d8d8',
  border: '#E5E5E6',
  inputBorder: '#c9c9cf',
  borderHover: '#b9b9bf',
  divider: '#e2e2e2',
  neutralSoft: '#e8e8e8',
  neutralHover: '#ececec',

  muted: '#6f6f6f',
  textMuted: '#696970',
  textSolid: '#141415',
  textSub: '#6D6B74',
  textFaint: '#8c8c94',
  textLight: '#b8b8b8',
  textLighter: '#bdbdbd',

  success: '#116329',
  successBorder: '#b8dec4',
  successSoft: '#eef8f1',
  successWash: '#f5fff7',
  danger: '#b42318',
  dangerDark: '#8f1d12',
  dangerSoft: '#fff0ed',
  dangerWash: '#fff1ef',
  google: '#4285f4',

  shadowLight: 'rgb(0 0 0 / 5%)',
  shadowSoft: 'rgb(0 0 0 / 8%)',
  shadowModal: 'rgb(0 0 0 / 10%)',
  shadowMedium: 'rgb(0 0 0 / 22%)',
  shadowDrawer: 'rgb(0 0 0 / 24%)',
  shadowStrong: 'rgb(0 0 0 / 38%)',
  overlayDim: 'rgb(0 0 0 / 42%)',
  overlayPage: 'rgb(4 2 16 /24%',
  blackWash: 'rgb(0 0 0 / 18%)',
  blackVeil: 'rgb(0 0 0 / 58%)',
  whiteInk: 'rgb(255 255 255 / 82%)',
  whiteSoft: 'rgb(255 255 255 / 78%)',
  whiteBorder: 'rgb(255 255 255 / 18%)',
  whiteBorderSoft: 'rgb(255 255 255 / 12%)',
  whiteOverlay: 'rgb(255 255 255 / 10%)',
  whiteOverlayHover: 'rgb(255 255 255 / 16%)',
  blackTransparent: 'rgb(5 5 5 / 0%)',
  blackImageWash: 'rgb(5 5 5 / 14%)',
  blackImageVeil: 'rgb(5 5 5 / 18%)',
  successAlpha: 'rgb(17 99 41 / 22%)',
  accentAlpha: 'rgb(185 81 27 / 18%)',
  accentStrongAlpha: 'rgb(206 95 24 / 30%)',
  accentRing: 'rgb(206 95 24 / 12%)',
} as const;

export const themeCssVariables = {
  '--color-primary': colors.primary,
  '--color-primary-hover': colors.primaryHover,
  '--color-accent': colors.accent,
  '--color-accent-dark': colors.accentDark,
  '--color-accent-strong': colors.accentStrong,
  '--color-accent-link': colors.accentLink,
  '--color-accent-bright': colors.accentBright,
  '--color-accent-button': colors.accentButton,
  '--color-accent-mark': colors.accentMark,
  '--color-accent-soft': colors.accentSoft,
  '--color-accent-tint': colors.accentTint,
  '--color-accent-wash': colors.accentWash,
  '--color-ink': colors.ink,
  '--color-ink-soft': colors.inkSoft,
  '--color-ink-muted': colors.inkMuted,
  '--color-ink-panel': colors.inkPanel,
  '--color-ink-body': colors.inkBody,
  '--color-ink-line': colors.inkLine,
  '--color-ink-gradient': colors.inkGradient,
  '--color-black': colors.black,
  '--color-apple-black': colors.appleBlack,
  '--color-paper': colors.paper,
  '--color-white': colors.white,
  '--color-soft': colors.soft,
  '--color-page': colors.page,
  '--color-surface-subtle': colors.surfaceSubtle,
  '--color-surface-raised': colors.surfaceRaised,
  '--color-input-soft': colors.inputSoft,
  '--color-line': colors.line,
  '--color-line-light': colors.lineLight,
  '--color-line-softer': colors.lineSofter,
  '--color-line-muted': colors.lineMuted,
  '--color-nav-muted': colors.navMuted,
  '--color-border': colors.border,
  '--color-input-border': colors.inputBorder,
  '--color-border-hover': colors.borderHover,
  '--color-divider': colors.divider,
  '--color-neutral-soft': colors.neutralSoft,
  '--color-neutral-hover': colors.neutralHover,
  '--color-muted': colors.muted,
  '--color-text-muted': colors.textMuted,
  '--color-text-sub': colors.textSub,
  '--color-text-faint': colors.textFaint,
  '--color-text-light': colors.textLight,
  '--color-text-lighter': colors.textLighter,
  '--color-success': colors.success,
  '--color-success-border': colors.successBorder,
  '--color-success-soft': colors.successSoft,
  '--color-success-wash': colors.successWash,
  '--color-danger': colors.danger,
  '--color-danger-dark': colors.dangerDark,
  '--color-danger-soft': colors.dangerSoft,
  '--color-danger-wash': colors.dangerWash,
  '--color-google': colors.google,
  '--shadow-light': colors.shadowLight,
  '--shadow-soft': colors.shadowSoft,
  '--shadow-modal': colors.shadowModal,
  '--shadow-medium': colors.shadowMedium,
  '--shadow-drawer': colors.shadowDrawer,
  '--shadow-strong': colors.shadowStrong,
  '--overlay-dim': colors.overlayDim,
  '--overlay-page': colors.overlayPage,
  '--wash-black': colors.blackWash,
  '--veil-black': colors.blackVeil,
  '--text-white-soft': colors.whiteInk,
  '--text-white-muted': colors.whiteSoft,
  '--border-white': colors.whiteBorder,
  '--border-white-soft': colors.whiteBorderSoft,
  '--overlay-white': colors.whiteOverlay,
  '--overlay-white-hover': colors.whiteOverlayHover,
  '--black-transparent': colors.blackTransparent,
  '--black-image-wash': colors.blackImageWash,
  '--black-image-veil': colors.blackImageVeil,
  '--success-alpha': colors.successAlpha,
  '--accent-alpha': colors.accentAlpha,
  '--accent-strong-alpha': colors.accentStrongAlpha,
  '--accent-ring': colors.accentRing,
} as const;

export const tailwindColors = {
  primary: colors.primary,
  accent: {
    DEFAULT: colors.accent,
    dark: colors.accentDark,
    strong: colors.accentStrong,
    link: colors.accentLink,
    bright: colors.accentBright,
    soft: colors.accentSoft,
  },
  ink: {
    DEFAULT: colors.ink,
    soft: colors.inkSoft,
    muted: colors.inkMuted,
    black: colors.black,
  },
  surface: {
    paper: colors.paper,
    soft: colors.soft,
    page: colors.page,
    subtle: colors.surfaceSubtle,
    raised: colors.surfaceRaised,
  },
  line: {
    DEFAULT: colors.line,
    light: colors.lineLight,
    muted: colors.lineMuted,
    border: colors.border,
  },
  text: {
    muted: colors.textMuted,
    subtle: colors.textSub,
    faint: colors.textFaint,
    light: colors.textLight,
  },
  success: {
    DEFAULT: colors.success,
    soft: colors.successSoft,
    wash: colors.successWash,
  },
  danger: {
    DEFAULT: colors.danger,
    dark: colors.dangerDark,
    soft: colors.dangerSoft,
    wash: colors.dangerWash,
  },
} as const;

export function applyThemeColors(root: HTMLElement = document.documentElement) {
  Object.entries(themeCssVariables).forEach(([token, value]) => {
    root.style.setProperty(token, value);
  });
}
